// <auto-generated />
using System;
using HotelBookings.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBookings.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241103155548_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBookings.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem Ipsum",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Fortune of time",
                            Occupancy = 4,
                            Price = 90.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lorem Ipsum",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Dark Skies",
                            Occupancy = 4,
                            Price = 120.0,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lorem Ipsum",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Fortune of time",
                            Occupancy = 4,
                            Price = 210.0,
                            Sqft = 550
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
